#!/bin/bash

# Simple Manual Startup - Run each command in a separate terminal

echo "=== Exchange Orderbook System - Manual Startup ==="
echo ""
echo "⚠️  IMPORTANT: You need to run each service in a SEPARATE terminal window"
echo ""
echo "Prerequisites:"
echo "1. Docker Desktop must be installed and running"
echo "2. All dependencies must be installed (run install-deps.sh first)"
echo ""
echo "=========================================="
echo "Terminal 1 - Docker Services"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/docker"
echo "docker compose up"
echo ""
echo "Wait 10 seconds, then continue..."
echo ""
echo "=========================================="
echo "Terminal 2 - Engine (Order Matching)"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/engine"
echo "npm run dev"
echo ""
echo "=========================================="
echo "Terminal 3 - API Server"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/api"
echo "npm run dev"
echo ""
echo "=========================================="
echo "Terminal 4 - WebSocket Server"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/ws"
echo "npm run dev"
echo ""
echo "=========================================="
echo "Terminal 5 - DB Processor"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/db"
echo "npm run dev"
echo ""
echo "=========================================="
echo "Terminal 6 - Frontend"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/frontend"
echo "npm run dev -- -p 3002"
echo ""
echo "=========================================="
echo "Terminal 7 - Market Maker (Optional)"
echo "=========================================="
echo "cd /Users/praveendhankhar/ExchangeOS/ExchangeOs/mm"
echo "npm run dev"
echo ""
echo "=========================================="
echo "Access the app at: http://localhost:3002/trade/TATA_INR"
echo "=========================================="
